<?php

/**
 * @file HTML Block Inject
 */

/**
 * Implementation of hook_block
 */
function _html_inject_config($delta = NULL) {
  $conf = array(
    array('name' => 'test1', 'url' => 'http://torchbox.com/',),
    array('name' => 'test2', 'url' => 'http://www.google.co.uk/',),
  );

  return ($delta === NULL) ? $conf : $conf[$delta];
}

/**
 * Implementation of hook_block
 */
function html_inject_block($op, $delta = 0, $edit = array()) {
  switch($op) {
    case 'list':
      $conf = _html_inject_config();
      foreach($conf as $i => $c) {
        $blocks[$i] = array('info' => $c['name']);
      }
      return $blocks;
    break;
    case 'view':
      $conf = _html_inject_config($delta);
      if (!$conf) { return; }
      $block['subject'] = $conf['name'];
      $r = drupal_http_request($conf['url']);
      if ($r->code == 200) {
      //  $block['content'] = $r->data;
        return $block;
      }
    break;
  }
}

function html_inject_preprocess_page(&$vars) {
  $r = drupal_http_request('http://www.torchbox.com/');

  $vars['content'] = $r->data;
}
